# Generated by Django 5.1.1 on 2024-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=255)),
                ('number_of_trees', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
    ]
